1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [22]:
m1 = np.array([[1, 2, 3], [4, 5, 6]], dtype='int8')
m2 = np.array([[11, 22, 33], [44, 55, 66]], dtype='int8')
print(f'm1\n{m1}\n')
print(f'm2\n{m2}\n')
print(f'm1 + m2\n{m1 + m2}')

m1
[[1 2 3]
 [4 5 6]]

m2
[[11 22 33]
 [44 55 66]]

m1 + m2
[[12 24 36]
 [48 60 72]]


2. Write a Python Program to Multiply Two Matrices?

In [23]:
m1 = np.array([[1, 2, 3], [4, 5, 6]], dtype='int8')
m2 = np.array([[11, 22], [33, 44], [55, 66]], dtype='int8')
print(f'm1\n{m1}\n')
print(f'm2\n{m2}\n')
print(f'm1 x m2\n{np.dot(m1, m2)}')

m1
[[1 2 3]
 [4 5 6]]

m2
[[11 22]
 [33 44]
 [55 66]]

m1 x m2
[[-14  52]
 [ 27 -64]]


3. Write a Python Program to Transpose a Matrix?

In [35]:
m1 = np.array([[11, 22], [33, 44], [55, 66]], dtype='int8')
print(f'm1\n{m1}\n')
print(f'Transpose of m1\n{m1.T}')

m1
[[11 22]
 [33 44]
 [55 66]]

Transpose of m1
[[11 33 55]
 [22 44 66]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [42]:
l = ['this', 'is', 'array', 'sort']
l.sort()
print(l)

['array', 'is', 'sort', 'this']


5. Write a Python Program to Remove Punctuation From a String?

In [55]:
import re
s = 'hello world! remove punctuations like ,.()[]{}^%&*'
print(s)
s = re.sub("[^\w\s]", "", s)
print(s)

hello world! remove punctuations like ,.()[]{}^%&*
hello world remove punctuations like 
